// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Helpdesk.RepositoryEf.Contexts;

#nullable disable

namespace Helpdesk.RepositoryEf.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220614202320_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Helpdesk.Core.Entities.AgencyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AgencyTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Settlement")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TownHall")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.ToTable("Agency");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Domicilio conocido",
                            AgencyTypeId = 1,
                            Code = "01",
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3938),
                            IsActive = true,
                            Log = "",
                            Name = "Principal",
                            Notes = "",
                            Phone = "",
                            ProjectId = 1,
                            Settlement = "",
                            State = "",
                            TownHall = "",
                            UserId = 1,
                            ZipCode = ""
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.AgencyTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("AgencyType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3911),
                            IsActive = true,
                            Name = "Corporativo"
                        },
                        new
                        {
                            Id = 2,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3914),
                            IsActive = true,
                            Name = "Matriz"
                        },
                        new
                        {
                            Id = 3,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3918),
                            IsActive = true,
                            Name = "Sucursal"
                        },
                        new
                        {
                            Id = 4,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3921),
                            IsActive = true,
                            Name = "Punto de venta"
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.PersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AgencyId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgencyId = 1,
                            LastName = "Admin",
                            Name = "Admin",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Project");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3809),
                            IsActive = true,
                            Name = "Proyecto inicial",
                            Notes = "Proyecto inicial",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Helpdesk.Core.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DateRegistration")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateRegistration = new DateTime(2022, 6, 14, 15, 23, 19, 930, DateTimeKind.Local).AddTicks(3969),
                            IsActive = true,
                            Name = "administrador",
                            Password = "123456",
                            PersonId = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
